openapi: 3.0.0
info:
  title: "EnTech"
  version: "1.0.0"
tags: 
- name: Surveys
paths:
  /Surveys:
    get:
      tags: 
        - "Surveys"
      operationId: getEnquetes
      summary: Obter Enquetes
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Enquete'
          description: OK
        '400': 
          description: Erro interno
    post:
      tags: 
          - "Surveys"
      operationId: postEnquetes
      summary: Criar Enquete
      requestBody: 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enquete'
      responses:
        '201':
          description: Enquete criada
        '400': 
          description: Erro interno


  /Surveys/{surveysId}:
      put:
        tags: 
            - "Surveys"
        operationId: putEnquetes
        summary: Alterar Enquete
        parameters:
          - name: surveysId
            in: path
            description: Identifier for Survey
            required: true
            schema:
              type: integer
              format: int64
        requestBody: 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enquete'
        responses:
          '200':
            description: Enquete alterada
          '400': 
            description: Erro interno
          '404': 
            description: Enquete não encontrada
      delete:
        tags: 
            - "Surveys"
        operationId: deleteEnquetes
        summary: Deletar Enquete
        parameters:
          - name: surveysId
            in: path
            description: Identifier for Survey
            required: true
            schema:
              type: integer
              format: int64
        responses:
          '200':
            description: Enquete deletada
          '400': 
            description: Erro interno
          '404': 
            description: Enquete não encontrada 
      get:
        tags: 
          - "Surveys"
        operationId: getEnquetesById
        summary: Obter Enquetes
        parameters:
          - name: surveysId
            in: path
            description: Identifier for Survey
            required: true
            schema:
              type: integer
              format: int64
        responses:
          '200':
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Enquete'
            description: OK
components:
  schemas:
    Enquete:
      type: object
      required: 
        - title
        - date
        - startTime
        - endTime
        - address
        - city
        - state
      properties:
        id:
          type: integer
          format: int64
          example: '123456'
        title:
          type: string
          example: 'Projetos da parceria PUC/DTI'
        date:
          type: string
          format: date
          example: '2019-05-14'
        startTime:
          type: string
          format: date-time
          example: 'T13:00:00'
        endTime:
          type: string
          format: date-time
          example: 'T15:00:00'
        address:
          type: string
          example: 'Rua dos Bobos, Nº 0'
        city:
          type: string
          example: 'Belo Horizonte'
        state:
          type: string
          minLength: 2
          maxLength: 2
          example: 'MG'
        photoURL:
          type: string
          example: 'https://api.com.br/imagem_id'
    users:
      required:
      - name
      - type
      - email
      - password
      - photoURL
      - status
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Alex Martins
        type:
          type: string
          example: Organizador
        email:
          type: string
          example: alex@entech.com.br
        password:
          type: string
          example: tecweb2019
        photoURL:
          type: string
          example: https://api.com.br/imagem_id
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/LucasASantos/EnTech/1.0.0